# k8s/kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraMounts:
      - hostPath: C:\mlops\projects\Titanic\data\raw
        containerPath: /mnt/raw
      - hostPath: C:\mlops\projects\Titanic\data\processed
        containerPath: /mnt/processed
      - hostPath: C:\mlops\projects\Titanic\models\artifacts
        containerPath: /mnt/models
      - hostPath: C:\mlops\projects\Titanic\logs
        containerPath: /mnt/logs
